# Generated by Django 3.2.4 on 2021-07-15 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('labels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_label',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('lebels', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='labels.label')),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='labels.video')),
                ('startTime', models.FloatField(default=0)),
                ('endTime', models.FloatField(default=0)),
                ('finish_flg', models.IntegerField(default=0))
            ],
        ),
        migrations.AlterField(
            model_name='video',
            name='show_to',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
