# Generated by Django 3.2.4 on 2021-07-15 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0003_auto_20210715_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='labels.label_types'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_label',
            name='type',
            field=models.ForeignKey(default = 1, on_delete=django.db.models.deletion.CASCADE, to='labels.label_types'),
            preserve_default=False,
        )
    ]
