# Generated by Django 3.2.4 on 2021-07-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0004_label_type'),
    ]

    operations = [

        migrations.AlterField(
            model_name='user_label',
            name='startTime',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='user_label',
            name='endTime',
            field=models.FloatField(),
        ),

        migrations.AlterField(
            model_name='user_label',
            name='finish_flg',
            field=models.IntegerField(),
        ),
    ]
